# Generated by Django 5.1.7 on 2025-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('avatar', models.TextField(default='/media/avatares/default-avatar.png')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
